### ISSUE TITLE
404 Not found Error

### ISSUE THREAD

**Issue by ishanjain28** [softprops/cargo-thanks#9]
I installed `cargo-thanks` using cargo, Created a token with `public_repo` permission and set the environment variable correctly but I keep getting "Error: 404 Not Found: 'Not Found'" error. 

My cargo.toml looks like this, 

```
[dependencies]
x11cap = "0.4.1"
gif = "0.9.2"
x11 = "2.16.0"
chrono = "0.4.0"
log = "0.3"
fern = "0.4"
rayon = "0.9.0"
```

It does sends "thanks" to `x11cap` but I think it's failing on `gif`.

**Comment by softprops** [comment]
I think I see the issue. My repository parsing isn't handing the case of repositories that end in .git 

https://github.com/PistonDevelopers/image-gif/blob/master/Cargo.toml#L9

It assumes GitHub urls that omit that. I'll fix that this evening

**Comment by ishanjain28** [comment]
@softprops  Thanks for taking note of this issue and Thanks for the awesome work. :)

**Comment by softprops** [comment]
ha, I only have others to thank ( no pun intended ). the rust community does so much awesome work. I can only help to promote that by amplifying that with star appreciation.

**Comment by softprops** [comment]
published a new version with a fix for this. `cargo install --force cargo-thanks` will get it you it.

```bash
$ cargo thanks
💖 fern github.com/daboross/fern
💖 x11cap github.com/bryal/X11Cap
💖 gif github.com/PistonDevelopers/image-gif.git
💖 rayon github.com/nikomatsakis/rayon
💖 log github.com/rust-lang/log
💖 chrono github.com/chronotope/chrono
💖 x11 github.com/Daggerbot/x11-rs.git
```
